name: Terraform CI

on:
  workflow_dispatch:
  push:
  #  paths:
  #    - 'modules/**'
  pull_request:
    paths:
      - 'modules/**'

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
    terraform:
        name: 'Terraform CI'
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v3
            with:
              terraform_version: 1.0.0

          - name: Create Terraform Plugin Cache Dir
            run: mkdir -p $TF_PLUGIN_CACHE_DIR

          - name: Cache Terraform
            uses: actions/cache@v4
            with:
              path: ${{ env.TF_PLUGIN_CACHE_DIR }}
              key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

          - name: Terraform validate modules
            run: |
              for dir in $(find ./modules -type d -mindepth 1 -maxdepth 1); do
                echo "Processing module $dir"
                terraform -chdir=$dir init -backend=false
                terraform -chdir=$dir validate
              done
